language: python
python:
  - "3.5"

install:
  - pip --version
  - pip install coverage coveralls twine
  - pip install pylint pydocstyle pycodestyle
  - pip install pyzmq

script: echo "Starting.."

jobs:
  include:
    - stage: lint
      script: bash ./travis/execute_linters.sh
    - stage: compile
      script: python setup.py install
    - stage: test
      script:  bash ./travis/execute_tests.sh
    - stage: deploy
      env: EXPECTED_FAILURE='TRUE'
      provider: pypi
      user: $PYPI_NAME
      password: $PYPI_PW
      on:
        tags: true
        branch: master



allow_failures:
  - env: EXPECTED_FAILURE='TRUE'

stages:
  - lint
  - compile
  - test
  - name: deploy
    if: branch = master


branches:
  only:
  - master
  - dev