slanguage: python
python:
  - "3.5"

install:
  - pip --version
  - pip install coverage coveralls
  - pip install pyzmq
 


# command to run tests
script:
  - coverage run --source=hermes setup.py test
  - coveralls

  - python3 tests.py



branches:
  only:
  - master
